name: Client/Server Check Tests CI

on:
  pull_request:
    branches: [master]

jobs:
  run_test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: create client environemnt
        run: |
          cd ./client
          npm ci
          touch .env
          echo NODE_ENV=development >> .env
          cat .env

      - name: test client
        run: |
          cd ./client
          npm run test

      - name: create server environemnt
        run: |
          cd ./server
          npm ci
          touch .env
          echo NODE_ENV=development >> .env
          cat .env

      - name: test server
        run: |
          cd ./server
          npm run test
